# Generated by Django 6.0.2 on 2026-02-10 04:26

from django.db import migrations, models
from django.utils.text import slugify


def populate_slugs(apps, schema_editor):
    PracticeArea = apps.get_model('pages', 'PracticeArea')
    for area in PracticeArea.objects.all():
        base_slug = slugify(area.name)
        slug = base_slug
        counter = 1
        while PracticeArea.objects.filter(slug=slug).exclude(pk=area.pk).exists():
            slug = f"{base_slug}-{counter}"
            counter += 1
        area.slug = slug
        area.save()


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='practicearea',
            name='slug',
            field=models.SlugField(blank=True, help_text='URL-friendly identifier', max_length=255),
        ),
        migrations.RunPython(populate_slugs, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='practicearea',
            name='slug',
            field=models.SlugField(help_text='URL-friendly identifier', max_length=255, unique=True),
        ),
    ]
