# Generated by Django 6.0 on 2025-12-16 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='practicearea',
            options={'verbose_name_plural': 'Practice Areas'},
        ),
        migrations.AddField(
            model_name='practicearea',
            name='featured_image',
            field=models.ImageField(blank=True, help_text='Main image displayed at the top of the page', null=True, upload_to='practice_areas/'),
        ),
        migrations.AddField(
            model_name='practicearea',
            name='gallery_images',
            field=models.JSONField(blank=True, default=list, help_text='List of image paths for gallery display (auto-managed)'),
        ),
    ]
