# Generated by Django 6.0 on 2025-12-16 06:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_alter_practicearea_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='practicearea',
            name='gallery_images',
        ),
        migrations.CreateModel(
            name='PracticeAreaImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='practice_areas/gallery/')),
                ('title', models.CharField(blank=True, help_text='Optional title for the image', max_length=255)),
                ('description', models.CharField(blank=True, help_text='Optional description for the image', max_length=500)),
                ('order', models.PositiveIntegerField(default=0, help_text='Order of images in gallery (lower numbers appear first)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('practice_area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery_images', to='pages.practicearea')),
            ],
            options={
                'verbose_name_plural': 'Practice Area Images',
                'ordering': ['order', '-created_at'],
            },
        ),
    ]
