# Generated by Django 6.0 on 2025-12-16 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0005_businesshours_holiday_appointment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attorney',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('job_title', models.CharField(help_text='e.g., Senior Attorney, Junior Attorney, Paralegal', max_length=255)),
                ('bio', models.TextField(blank=True, help_text='Professional biography')),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('photo', models.ImageField(help_text='Professional photo of the attorney', upload_to='attorneys/')),
                ('order', models.PositiveIntegerField(default=0, help_text='Order of appearance on the team page (lower numbers appear first)')),
                ('is_active', models.BooleanField(default=True, help_text='Whether to display this attorney on the website')),
                ('specializations', models.CharField(blank=True, help_text='Comma-separated list of practice areas', max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Attorneys',
                'ordering': ['order', 'last_name', 'first_name'],
            },
        ),
    ]
