# Generated by Django 6.0 on 2025-12-16 18:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0006_attorney'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='attorney',
            options={'ordering': ['order', 'full_name'], 'verbose_name_plural': 'Attorneys'},
        ),
        migrations.RenameField(
            model_name='attorney',
            old_name='first_name',
            new_name='full_name',
        ),
        migrations.RemoveField(
            model_name='attorney',
            name='last_name',
        ),
    ]
