# Generated by Django 6.0 on 2025-12-16 18:46

import django.utils.timezone
from django.db import migrations, models


def populate_slugs(apps, schema_editor):
    """Populate slug field with unique slugs based on full_name"""
    Attorney = apps.get_model('pages', 'Attorney')
    
    for attorney in Attorney.objects.all():
        # Generate base slug from full_name
        base_slug = attorney.full_name.lower().replace(' ', '-').replace('.', '').replace("'", '')
        base_slug = ''.join(c for c in base_slug if c.isalnum() or c == '-')
        slug = base_slug
        
        # Handle duplicates by adding a number suffix
        counter = 1
        while Attorney.objects.filter(slug=slug).exclude(pk=attorney.pk).exists():
            slug = f"{base_slug}-{counter}"
            counter += 1
        
        attorney.slug = slug
        attorney.save()


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0007_change_attorney_to_full_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='attorney',
            name='slug',
            field=models.SlugField(default='', help_text='URL-friendly identifier', max_length=255),
            preserve_default=False,
        ),
        migrations.RunPython(populate_slugs),
        migrations.AlterField(
            model_name='attorney',
            name='slug',
            field=models.SlugField(help_text='URL-friendly identifier', max_length=255, unique=True),
        ),
    ]
