# Generated by Django 6.0 on 2025-12-17 03:20

import django_ckeditor_5.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0008_add_attorney_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, unique=True)),
                ('slug', models.SlugField(help_text='URL-friendly identifier', max_length=255, unique=True)),
                ('author', models.CharField(help_text='Name of the blog author', max_length=255)),
                ('featured_image', models.ImageField(blank=True, help_text='Featured image for the blog post', null=True, upload_to='blogs/')),
                ('excerpt', models.TextField(help_text='Short summary of the blog post', max_length=500)),
                ('content', django_ckeditor_5.fields.CKEditor5Field(help_text='Main content of the blog post')),
                ('category', models.CharField(blank=True, help_text='Blog category/topic', max_length=100)),
                ('published_date', models.DateField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('is_published', models.BooleanField(default=True, help_text='Whether this blog is visible on the website')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Blogs',
                'ordering': ['-published_date'],
                'indexes': [models.Index(fields=['-published_date'], name='pages_blog_publish_f142d8_idx'), models.Index(fields=['slug'], name='pages_blog_slug_09fc28_idx'), models.Index(fields=['is_published'], name='pages_blog_is_publ_b56172_idx')],
            },
        ),
    ]
