# Generated by Django 6.0 on 2025-12-19 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0009_blog'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attorney',
            name='bio',
        ),
        migrations.AddField(
            model_name='attorney',
            name='professional_background',
            field=models.TextField(blank=True, help_text='Detailed professional background and biography'),
        ),
        migrations.AddField(
            model_name='attorney',
            name='short_bio',
            field=models.TextField(blank=True, help_text='Brief personal statement or tagline (max 300 characters)', max_length=300),
        ),
    ]
